export const ERROR_CODES = {
  MISSING_COMMAND: 'MISSING_COMMAND',
  UNKNOWN_COMMAND: 'UNKNOWN_COMMAND',
  UNKNOWN_OPTION: 'UNKNOWN_OPTION',
  INVALID_INVOCATION: 'INVALID_INVOCATION',
  DELIVERY_ENGINE_NOT_IMPLEMENTED: 'DELIVERY_ENGINE_NOT_IMPLEMENTED',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  COMPATIBILITY_UNSUPPORTED: 'COMPATIBILITY_UNSUPPORTED',
  DOCS_TOPIC_NOT_FOUND: 'DOCS_TOPIC_NOT_FOUND',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
